### ISSUE TITLE
What's your favorite board game?

### ISSUE THREAD

**Issue by agarrharr** [joeeames/ama#2]

**Comment by joeeames** [comment]
Right now it's probably **Favor of the Pharoah**. Something about the dice rolling in that game really speaks to me. I also love games where something can happen that makes everyone cheer. For that reason my second favorite is **Camel Up**. Some hilarious and crazy stuff can happen in that game.

Honorable Mentions (roughly in order):
Lords of Vegas
The Prodigal's Club
Broom Service
Alchemists
Last Will
Legendary

I could definitely name a bunch more games though.
