### ISSUE TITLE
What's your phone homescreen look like

### ISSUE THREAD

**Issue by kentcdodds** [joeeames/ama#4]
A screenshot please :-) This tells a lot about a person. [Here's mine](https://github.com/kentcdodds/ama/issues/5)

**Comment by joeeames** [comment]
It's basically this picture cropped differently.

http://darksideconfidential.com/wp-content/uploads/2015/09/BB-8-for-featured-image.jpg

**Comment by kentcdodds** [comment]
I'm interested in what apps you value enough to be on the homescreen though :-)

**Comment by joeeames** [comment]
![screenshot_20160406-112913](https://cloud.githubusercontent.com/assets/1072285/14327492/c075e5ac-fbef-11e5-8a5a-2a00f5951a07.png)
